# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install mercurial
      run: brew install mercurial
    
    - name: Install cinnabar
      run: brew install git-cinnabar
 
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
      
    - name: Android NDK toolchain Setup
      run: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.0.6113669" "cmake;3.10.2.4988404"
        
    - name: Install latest nightly rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
          target: aarch64-linux-android 

    - name: views
      run: |
        hg --version
        source $HOME/.cargo/env

    - name: fetch geckoview code
      run: |
        git init gecko && cd gecko
        git config fetch.prune true
        git config push.default upstream
        git remote add central hg::https://hg.mozilla.org/mozilla-central -t branches/default/tip
        git remote add inbound hg::https://hg.mozilla.org/integration/mozilla-inbound -t branches/default/tip
        git remote set-url --push central hg::ssh://hg.mozilla.org/mozilla-central
        git remote set-url --push inbound hg::ssh://hg.mozilla.org/integration/mozilla-inbound
        git config remote.central.fetch +refs/heads/branches/default/tip:refs/remotes/central/default
        git remote add try hg::https://hg.mozilla.org/try
        git config remote.try.skipDefaultUpdate true
        git remote set-url --push try hg::ssh://hg.mozilla.org/try
        git config remote.try.push +HEAD:refs/heads/branches/default/tip
        git remote update
        git checkout central/default
        
    - name: xcode and bootstrap
      run: |
        sudo xcode-select  --switch /Applications/Xcode.app 
        ./mach bootstrap
        
    - name: mozconfig gen
      run: |   
        echo 'ac_add_options --enable-application=mobile/android' > mozconfig 
        echo '\n' >> mozconfig
        echo 'ac_add_options --target=aarch64' >> mozconfig
        
    - name: build out
      run: |  
        ./mach configure
        ./mach build
        ./mach package 
        
