# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install mercurial
      run: brew install mercurial
    
    - name: Install cinnabar
      run: brew install git-cinnabar
 
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
      
    - name: Android NDK toolchain Setup
      uses: ravinderjangra/android-ndk-toolchain-setup@0.1
      with:
          api: '21'
          arch: 'aarch64'
          install-location: 'toolchains'
          force: true
        
    - name: Run rust install
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        source $HOME/.cargo/env
        rustup target add aarch64-linux-android

    # Runs a set of commands using the runners shell
    - name: Run code clone
      run: |
        hg --version
        source $HOME/.cargo/env
        git init gecko && cd gecko
        git config fetch.prune true
        git config push.default upstream
        git remote add central hg::https://hg.mozilla.org/mozilla-central -t branches/default/tip
        git remote add inbound hg::https://hg.mozilla.org/integration/mozilla-inbound -t branches/default/tip
        git remote set-url --push central hg::ssh://hg.mozilla.org/mozilla-central
        git remote set-url --push inbound hg::ssh://hg.mozilla.org/integration/mozilla-inbound
        git config remote.central.fetch +refs/heads/branches/default/tip:refs/remotes/central/default
        git remote add try hg::https://hg.mozilla.org/try
        git config remote.try.skipDefaultUpdate true
        git remote set-url --push try hg::ssh://hg.mozilla.org/try
        git config remote.try.push +HEAD:refs/heads/branches/default/tip
        git remote update
        git checkout central/default
        sudo xcode-select  --switch /Applications/Xcode.app 
        ./mach bootstrap –no-interactive
        echo 'ac_add_options --enable-application=mobile/android' > mozconfig 
        echo '\n' >> mozconfig
        echo 'ac_add_options --target=aarch64' >> mozconfig
        ./mach configure
        ./mach build
        ./mach package 
        
